<%@ Page Title="Create Mailing" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Create.aspx.cs" Inherits="EmailQueueApp.Create" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <form>
        <div class="form-group">
            <asp:Label runat="server" CssClass="control-label">Subject</asp:Label>
            <asp:TextBox runat="server" ID="Subject" CssClass="form-control"></asp:TextBox>
        </div>

        <div class="form-group">
            <asp:Label runat="server" CssClass="control-label">Body</asp:Label>
            <asp:TextBox runat="server" ID="Body" TextMode="MultiLine" CssClass="form-control"></asp:TextBox>
        </div>

        <div class="form-group">
            <asp:Label runat="server" CssClass="control-label">Addresses</asp:Label>
            
            <asp:GridView runat="server" ID="Addresses"
                ItemType="EmailQueueApp.ViewModel.AddressPM"
                AutoGenerateColumns="true"
                AutoGenerateEditButton="true"
                AutoGenerateDeleteButton="true"
                CssClass="table table-hover table-bordered"
                UpdateMethod="Addresses_UpdateItem"
                DeleteMethod="Addresses_DeleteItem"
                SelectMethod="Addresses_GetData">
            </asp:GridView>
        </div>

        <div class="form-group">
            <asp:Button runat="server" ID="CreateBtn" CssClass="btn btn-primary" Text="Create" OnClick="CreateBtn_Click" />
        </div>
    </form>
</asp:Content>
